# Generated by Django 5.0.1 on 2026-03-03 16:41

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        db_index=True,
                        help_text="Unique key to prevent duplicate transactions",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("DEPOSIT", "Deposit"),
                            ("WITHDRAWAL", "Withdrawal"),
                            ("TRANSFER", "Transfer"),
                        ],
                        help_text="Type of transaction",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="PENDING",
                        help_text="Current status of the transaction",
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Transaction amount",
                        max_digits=20,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="NGN", help_text="Currency code", max_length=3
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        db_index=True,
                        help_text="Human-readable transaction reference",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Transaction description"),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional transaction metadata",
                    ),
                ),
                (
                    "initiated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who initiated the transaction",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="initiated_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transactions",
                "db_table": "transactions",
            },
        ),
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="NGN",
                        help_text="Currency code (ISO 4217)",
                        max_length=3,
                    ),
                ),
                (
                    "is_system",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="True if this is a system wallet (for deposits/withdrawals)",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Wallet name/description", max_length=100
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Owner of the wallet (null for system wallets)",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="wallets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Wallet",
                "verbose_name_plural": "Wallets",
                "db_table": "wallets",
            },
        ),
        migrations.CreateModel(
            name="LedgerEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "entry_type",
                    models.CharField(
                        choices=[("DEBIT", "Debit"), ("CREDIT", "Credit")],
                        help_text="Debit or Credit",
                        max_length=10,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Entry amount (always positive)",
                        max_digits=20,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "balance_after",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Cached running balance after this entry",
                        max_digits=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Entry description"),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        help_text="Transaction this entry is part of",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ledger_entries",
                        to="wallets.transaction",
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        help_text="Wallet this entry belongs to",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ledger_entries",
                        to="wallets.wallet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ledger Entry",
                "verbose_name_plural": "Ledger Entries",
                "db_table": "ledger_entries",
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["-created_at"], name="transaction_created_cf5536_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["status", "-created_at"], name="transaction_status_b84006_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["transaction_type", "-created_at"],
                name="transaction_transac_a32e0c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="wallet",
            index=models.Index(
                fields=["user", "currency"], name="wallets_user_id_84225e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wallet",
            index=models.Index(fields=["is_system"], name="wallets_is_syst_004107_idx"),
        ),
        migrations.AddConstraint(
            model_name="wallet",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_system", False)),
                fields=("user", "currency"),
                name="unique_user_currency_wallet",
            ),
        ),
        migrations.AddConstraint(
            model_name="wallet",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("is_system", True), ("user__isnull", True)),
                    models.Q(("is_system", False), ("user__isnull", False)),
                    _connector="OR",
                ),
                name="system_wallet_has_no_user",
            ),
        ),
        migrations.AddIndex(
            model_name="ledgerentry",
            index=models.Index(
                fields=["wallet", "-created_at"], name="ledger_entr_wallet__b56567_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ledgerentry",
            index=models.Index(
                fields=["transaction"], name="ledger_entr_transac_16a1ad_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ledgerentry",
            index=models.Index(
                fields=["entry_type"], name="ledger_entr_entry_t_b01434_idx"
            ),
        ),
    ]
