# Generated by Django 5.0.1 on 2026-03-08 17:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="wallet",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_system", True)),
                fields=("is_system", "currency"),
                name="unique_system_wallet_per_currency",
            ),
        ),
    ]
