# Generated by Django 5.0.1 on 2026-03-03 16:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReconciliationReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "run_type",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Scheduled(Daily)"),
                            ("MANUAL", "Manual Trigger"),
                            ("POST_TRANSACTION", "Post-Transaction"),
                        ],
                        default="SCHEDULED",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RUNNING", "Running"),
                            ("PASSED", "Passed"),
                            ("WARNING", "Warning"),
                            ("FAILED", "Failed"),
                            ("CRITICAL", "Critical"),
                        ],
                        db_index=True,
                        default="RUNNING",
                        help_text="Status of this reconciliation run",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("duration_seconds", models.FloatField(blank=True, null=True)),
                (
                    "checks_summary",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Summary of each check (passed/failed, issue count)",
                    ),
                ),
                (
                    "discrepancies",
                    models.JSONField(
                        blank=True, default=list, help_text="List of all issues found"
                    ),
                ),
                (
                    "statistics",
                    models.JSONField(
                        blank=True, default=dict, help_text="Overall system statistics"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Admin notes or actions taken"
                    ),
                ),
                (
                    "triggered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reconciliation_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Reconciliation Report",
                "verbose_name_plural": "Reconciliation Reports",
                "db_table": "reconciliation_reports",
                "indexes": [
                    models.Index(
                        fields=["-started_at"], name="reconciliat_started_e9d4c6_idx"
                    ),
                    models.Index(
                        fields=["status", "-started_at"],
                        name="reconciliat_status_2d2fb5_idx",
                    ),
                ],
            },
        ),
    ]
