# Generated by Django 5.0.1 on 2026-02-27 23:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ReconciliationReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RUNNING", "Running"),
                            ("PASSED", "Passed"),
                            ("FAILED", "Failed"),
                        ],
                        default="RUNNING",
                        help_text="Status of this reconciliation run",
                        max_length=20,
                    ),
                ),
                (
                    "run_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this reconciliation was run"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this reconciliation completed",
                        null=True,
                    ),
                ),
                (
                    "checks_performed",
                    models.JSONField(
                        default=list, help_text="List of checks performed"
                    ),
                ),
                (
                    "discrepancies",
                    models.JSONField(
                        default=list, help_text="List of discrepancies found"
                    ),
                ),
                (
                    "summary",
                    models.JSONField(default=dict, help_text="Summary statistics"),
                ),
                ("notes", models.TextField(blank=True, help_text="Additional notes")),
            ],
            options={
                "verbose_name": "Reconciliation Report",
                "verbose_name_plural": "Reconciliation Reports",
                "db_table": "reconciliation_reports",
                "indexes": [
                    models.Index(
                        fields=["-run_at"], name="reconciliat_run_at_b55c68_idx"
                    ),
                    models.Index(
                        fields=["status"], name="reconciliat_status_966ac4_idx"
                    ),
                ],
            },
        ),
    ]
