# Generated by Django 5.0.1 on 2026-03-11 15:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reconciliation", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reconciliationreport",
            name="status",
            field=models.CharField(
                choices=[
                    ("RUNNING", "Running"),
                    ("PASSED", "Passed"),
                    ("WARNING", "Warning"),
                    ("FAILED", "Failed"),
                    ("CRITICAL", "Critical"),
                    ("PENDING", "Pending"),
                ],
                db_index=True,
                default="RUNNING",
                help_text="Status of this reconciliation run",
                max_length=20,
                null=True,
            ),
        ),
    ]
