# Generated by Django 5.0.1 on 2026-03-03 16:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        db_index=True,
                        help_text="Action performed (e.g., DEPOSIT, WITHDRAW, TRANSFER)",
                        max_length=100,
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        db_index=True,
                        help_text="Type of entity affected (e.g., Wallet, Transaction)",
                        max_length=50,
                    ),
                ),
                (
                    "target_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="ID of the affected entity",
                        null=True,
                    ),
                ),
                (
                    "changes",
                    models.JSONField(
                        blank=True, default=dict, help_text="Details of the change"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address of the request", null=True
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True, default="", help_text="User agent string"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional metadata"
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who performed the action",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "db_table": "audit_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="audit_logs_created_43fcd6_idx"
                    ),
                    models.Index(
                        fields=["actor", "-created_at"],
                        name="audit_logs_actor_i_3b0e80_idx",
                    ),
                    models.Index(
                        fields=["action", "-created_at"],
                        name="audit_logs_action_bcaa71_idx",
                    ),
                    models.Index(
                        fields=["target_type", "target_id"],
                        name="audit_logs_target__9fc8de_idx",
                    ),
                ],
            },
        ),
    ]
