# Generated by Django 5.0.1 on 2026-02-27 23:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        db_index=True,
                        help_text="Action performed (e.g., DEPOSIT, WITHDRAW, TRANSFER)",
                        max_length=100,
                    ),
                ),
                ("object_id", models.UUIDField(blank=True, null=True)),
                (
                    "old_state",
                    models.JSONField(
                        blank=True, help_text="State before the action", null=True
                    ),
                ),
                (
                    "new_state",
                    models.JSONField(
                        blank=True, help_text="State after the action", null=True
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address of the request", null=True
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, help_text="User agent string"),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional metadata"
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who performed the action",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "db_table": "audit_logs",
                "permissions": [
                    ("can_view_sensitive_view_auditlog", "Can view audit logs")
                ],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="audit_logs_created_43fcd6_idx"
                    ),
                    models.Index(
                        fields=["actor", "-created_at"],
                        name="audit_logs_actor_i_3b0e80_idx",
                    ),
                    models.Index(
                        fields=["action", "-created_at"],
                        name="audit_logs_action_bcaa71_idx",
                    ),
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="audit_logs_content_b0ef47_idx",
                    ),
                ],
            },
        ),
    ]
